export const actionTypes = {
    UPDATE_USERNAME: 'UPDATE_USERNAME',
    LOGGED_IN: 'LOGGED_IN',
    UPDATE_INBOX: 'UPDATE_INBOX',
    UPDATE_SENT: 'UPDATE_SENT',
    CLOSE_PROMPT: 'CLOSE_PROMPT',
    OPEN_PROMPT: 'OPEN_PROMPT',
    TOGGLE_SUCCESS: 'TOGGLE_SUCCESS',
    LOADING: 'LOADING',
    FINISHED_LOADING: 'FINISHED_LOADING',
    IS_DELETE: 'IS_DELETE',
    IS_DELETE_FINISHED: 'IS_DELETE_FINISHED',
    SET_ID_TO_DELETE: 'SET_ID_TO_DELETE'
}