export const actionTypes = {
    UPDATE_USERNAME: 'UPDATE_USERNAME',
    LOGGED_IN: 'LOGGED_IN',
    CLOSE_PROMPT: 'CLOSE_PROMPT',
    OPEN_PROMPT: 'OPEN_PROMPT',
    LOADING: 'LOADING',
    FINISHED_LOADING: 'FINISHED_LOADING',
    UPDATE_TOKEN: 'UPDATE_TOKEN'
}